### ISSUE TITLE
Get nft owner history does not include initial send block

### ISSUE THREAD

**Issue by udbhav-s** [BananoCoin/banano-metanode-nft#20]
Example block: `A61110DC676B0405D507342CD4679C1842867BABE5CEA1A4FEAD5D81EC4A4D75`  
(Template `Qmf3kndfvzLW6RDcnAne6xcdgKXg2NCXfZHjLUnAmaad6q`)  

Response from `get_nft_asset_owner` has an empty history array (should include the initial send that minted the block):  
![image](https://user-images.githubusercontent.com/50021387/127686345-7788a191-2493-4a26-8767-f73b47ece950.png)

**Comment by coranos** [comment]
now shows
Asset:A61110DC676B0405D507342CD4679C1842867BABE5CEA1A4FEAD5D81EC4A4D75
Asset Owner:ban_3dbwwneas58hr8ihhrtt4616gh4wzasuj5p85xohfbmr6nmyd7z1ret8bac4
Asset Account:ban_3bij45g8gtr61qcigf3etjmsr844isxtqsggn8khxdcxi9p6nmdoyppi9x5i
A61110DC676B0405D507342CD4679C1842867BABE5CEA1A4FEAD5D81EC4A4D75=>=ban_3dbwwneas58hr8ihhrtt4616gh4wzasuj5p85xohfbmr6nmyd7z1ret8bac4

**Comment by coranos** [comment]
reopened issue as i did it wrong. only checked first send and not last send.
