### ISSUE TITLE
banano-ipfs lib

### ISSUE THREAD

**Issue by Airtune** [BananoCoin/banano-metanode-nft#5]
handle conversion between ipfs v0 cids and banano addresses in separate module

**Comment by Airtune** [comment]
I made a pull-request where I moved the logic for converting between IPFS CIDs and Banano addresses into a separate library.
If you're not comfortable with the package set directly to `github:Airtune/banano-ipfs` in `package.json, fork the library and change it to `github:BananoCoin/banano-ipfs`.

**Comment by coranos** [comment]
moved to https://github.com/BananoCoin/banano-ipfs

and added some code coverage and fixed some docs. will merge to ipfs

**Comment by coranos** [comment]
npm @bananocoin/banano-ipfs
