### ISSUE TITLE
Validate IPFS data using hash in CID when fetching from gateway

### ISSUE THREAD

**Issue by Airtune** [BananoCoin/banano-metanode-nft#7]

**Comment by coranos** [comment]
a question on this issue:

Do you want me to validate that the CID to the template points to valid JSON? (I do this)

Or do you want me to validate that the CID in the template JSON points to valid IPFS data? (I do not do this)

If the template points to an image that was unpinned, that would be a problem.

I could try doing a http HEAD in front of the http GET, to see if the resource exists first.

**Comment by Airtune** [comment]
The SHA-256 is collision resistant enough that simply verifying the checksum stored in the ledger should be sufficient.

Handling missing data is a whole other issue.
