### ISSUE TITLE
Check confirmations when using account_history RPC

### ISSUE THREAD

**Issue by Airtune** [BananoCoin/banano-metanode-nft#8]
`account_history` also returns unconfirmed blocks
https://docs.nano.org/commands/rpc-protocol/#account_history

To make sure we're not getting any double spends, also check confirmations.

https://docs.nano.org/commands/rpc-protocol/#account_info
From Nano node v19.0+, `confirmation_height` is available in the `account_info` RPC.

Otherwise checking `block_info` for the frontier to see if `"confirmed": "true"` also works.

**Comment by coranos** [comment]
fixed in latest commit

https://github.com/BananoCoin/banano-metanode-nft/commit/f52988f0e831e217c58921c1d3b824813af35147#diff-e6792d3c43b1957b215b4aa69ebeb91915c017f44c1726b59d57c71b1d7ad6e7R465

'reached confirmed frontier with no next asset owner'.
